config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]

  as :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end

  unauthenticated do
    root "splash_screen#index", as: :unauthenticated_root
  end

  resources :categories, only: [:index, :new, :show, :create] do
    resources :details, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else

      can :read, [Category, Detail]
      can :create, [Category, Detail]
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_details, dependent: :destroy
  has_many :details, through: :category_details

  validates :name, presence: true
  validates :icon_url, presence: true
end

app/models/category_detail.rb
class CategoryDetail < ApplicationRecord
  belongs_to :category
  belongs_to :detail
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :user
  has_many :category_details, dependent: :destroy
  has_many :categories, through: :category_details

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :details, dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def admin?
    role == 'admin'
  end

  def guest?
    role == 'guest'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.includes(:details, :user).where(user: current_user)
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon_url)
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[edit update destroy]

  def index
    @category = Category.find_by_id(params[:category_id])
    @details = @category.details.order(created_at: :desc)
  end

  def show
    @detail = Detail.find_by(id: params[:id])
    @details = @detail.details.order(created_at: :desc)
  end

  def new
    @detail = Detail.new
    @category = Category.find(params[:category_id])
    @categories = Category.where(user_id: current_user.id)
  end

  def edit; end

  def create
    @category = Category.includes(:user).find_by(id: params[:category_id])
    @detail = Detail.new(detail_params)
    @detail.category_ids = [@category.id]
    @detail.user_id = current_user.id

    respond_to do |format|
      if @detail.save
        format.html { redirect_to category_details_path(@category), notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_detail
    @detail = Detail.find(params[:id])
  end

  def detail_params
    params.require(:detail).permit(:name, :amount)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    # @users = User.all
    authorize! :index, @users
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    authorize! :create, @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = current_user.id
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="owner">
  <% if @current_owner != category.user %>
    <p>
      <strong>Name:</strong>
      <%= category.user.name %>
    </p>
    <% @current_owner = category.user %>
  <% end %>
</div>

<div class="cate-container" id="<%= dom_id category %>">
  <div>
    <img src="<%= category.icon_url %>" alt="Category Icon" width="100" height="100">
  </div>

  <div>
    <p>
      <%= category.name %>
    </p>
  
    <p>
      <strong>$</strong>
      <%= category.details.sum(:amount) %>
    </p>

    <p>
      <%= link_to "View details", category_details_path(category) %>
    </p>
  </div>
  
</div>

app/views/categories/_form.html.erb
<section class="form-container">
  <nav>
    <%= link_to raw('&larr;'), authenticated_root_path, class: "arrow-link" %>
    <h2>TRANSACTIONS</h2>
    <p class="sign-out">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </p>
  </nav>

  <div class="add-cate">
    <%= form_with(model: category) do |form| %>
      <% if category.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :icon_url, style: "display: block" %>
        <%= form.text_field :icon_url %>
      </div>

      <div class="field">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</section>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<section class="form-container">
  <p style="color: green"><%= notice %></p>
  <nav>
    <%= link_to raw('&larr;'), new_user_session_path, class: "arrow-link" %>
    <h2>TRANSACTIONS</h2>
    <p class="sign-out">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </p>
  </nav>

  <div id="categories">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
  <div class="new-cate">
    <%= link_to "New category", new_category_path %>
  </div>
</section>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

<br>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>|
  <%= link_to "Add transection", new_category_detail_path(@category) %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/details/_detail.html.erb
<div id="<%= dom_id detail %>">
  <h2><%= detail.name %></h2>
  <p>Amount: <%= detail.amount %></p>
</div>

app/views/details/_form.html.erb
<section class="form-container">
  <nav>
    <%= link_to raw('&larr;'), authenticated_root_path, class: "arrow-link" %>
    <h2>DETAILS</h2>
    <p class="sign-out">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </p>
  </nav>
  <%= form_with(model: @detail, url: category_details_path) do |form| %>
    <% if @detail.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

        <ul>
          <% @detail.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :amount, style: "display: block" %>
      <%= form.text_field :amount %>
    </div>

    <div class="field">
      <%= form.submit %>
    </div>
  <% end %>
</section>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Show this detail", @detail %> |
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/index.html.erb
<section class="form-container">
  <p style="color: green"><%= notice %></p>
  <nav>
    <%= link_to raw('&larr;'), authenticated_root_path, class: "arrow-link" %>
    <h2>DETAILS</h2>
    <p class="sign-out">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </p>
  </nav>

  <p class="total-d"><strong>Total Amount:</strong> <%= number_to_currency(@category.details.sum(:amount)) %></p>
  <div class="trans">
    <h1>Transactions for <%= @category.name %></h1>
    <div id="details">
      <% if @details.empty? %>
        <p>No details found for this category.</p>
      <% else %>
        <% @details.each do |detail| %>
          <%= render detail %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class= "new-cate space">
    <%= link_to "Add New Transaction", new_category_detail_path(@category) %>
  </div>
</section>

app/views/details/new.html.erb
<%= render "form", detail: @detail %>

<br>

app/views/details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detail %>

<div>
  <%= link_to "Edit this detail", edit_detail_path(@detail) %> |
  <%= link_to "Back to details", details_path %>

  <%= button_to "Destroy this detail", @detail, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="screen">
  <h1>Finance Wallet</h1>
  <div>
    <a href="<%= new_user_session_path %>" class="login-btn">Login</a>
    <a href="<%= new_user_registration_path %>" class="signup-btn">Sign Up</a>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prevented this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>